### ISSUE TITLE
Issue with .format

### ISSUE THREAD

**Issue by jpmeijers** [MartinSGill/ICS-Cards-Download-Statements#1]
```
jpmeijers@<redacted>:~/ICS-Cards-Download-Statements$ python3 DownloadStatement.py <redacted> <redacted>
Traceback (most recent call last):
  File "DownloadStatement.py", line 304, in <module>
    main()
  File "DownloadStatement.py", line 275, in main
    filename = "{0:04d}-{1:02d}_to_{2:04d}-{3:02d}.{4}".format(year, month, end_year, end_month, format)
TypeError: unsupported format string passed to NoneType.__format__
```

Getting this error when running the script. Does this script still work with the current ICS Cards website, or is this a python version issue?

**Comment by MartinSGill** [comment]
I've not used the script for a number of years. It might therefore be both.
I believe I wrote the script against python 2.7.

**Comment by dan-griffiths-dev** [comment]
Hi Martin, you mention you don't use the script, so wondering how you obtain your credit card transactions now
